### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by Wade821** [cfbao/google-drive-trash-cleaner#10]
I made a mini script for this program so I can schedule it to automatically run in Windows using the task scheduler (because my mother would never run it herself). This is the command I run when attempting to clean the drive within the script itself.

`cleaner -a -d 7 -m`

The executable should be the most up to date version, dated 2/2/2018 or version 1.1.2 which is what I have downloaded notated in the readme notepad document I made. This is what happens after I let it run...

![image](https://user-images.githubusercontent.com/18544575/53464534-ca04b900-3a07-11e9-9eb1-16ad78a34394.png)

Needless to say, this is problematic. It appears the python script was updated here but I don't know how to convert that to a binary as I'm not a programmer myself. More repair/custom rig building oriented with some scripting knowledge. Hoping for a possible answer on this. The full script I use is below. Hopefully this is enough information to assist. 

```
@echo off
title Google Drive Trash Files Cleanup
if not DEFINED IS_MINIMIZED set IS_MINIMIZED=1 && start "" /min "%~dpnx0" %* && exit

cd "%userprofile%\Downloads\Google Drive Cleaner"

echo Do not close this window! It is clearing up space so
echo Google Drive works properly for files over 7 days old.
echo.
cleaner -a -d 7 -m
echo.
echo Process finished. Closing soon . . .
echo.
timeout /t 10
exit
```

**Edit:** It appears after running it several times with the error that it was able to go through and clean the trashcan all up finally. But I'll leave the post here in case there's something else that might need to be done. :)

**Comment by cfbao** [comment]
I have an idea what's wrong here. Will fix once I've got a bit more time.
In the mean time, running the script multiple times should be enough to always get it through.

**Comment by cfbao** [comment]
Project deprecated. See [ReadMe](https://github.com/cfbao/google-drive-trash-cleaner/blob/master/README.md).
