### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by station7** [cfbao/google-drive-trash-cleaner#12]
After re-activating my google account, I am unable to authenticate google-drive-trash-cleaner. When I paste the link into my browser, I get the following message: _Sign in with Google temporarily disabled for this app._ 

Any chance to get this resolved and authenticate google-drive-trash-cleaner again? Maybe a manual workaround?

**Comment by cfbao** [comment]
Damn... This app has already reached the 100 user limit for an unverified app.
I've been dragging my feet too lazy to have it verified it for quite a while, but I guess I have to do this now.

A workaround would be obtaining your own client id & client secret, and place them in the `CLIENT_CREDENTIAL` variable in the script "cleaner.py".

Some random articles on how to obtain Google client ID & secret:
https://www.balbooa.com/gridbox-documentation/how-to-get-google-client-id-and-client-secret
https://theonetechnologies.com/blog/post/how-to-get-google-app-client-id-and-client-secret

**Comment by station7** [comment]
Hi cfbao, many thanks for your reply! I really love this litte script running on my RPi and I appreciate that you still monitor this repo and maybe even fix this... Thank you so much!

**Comment by ANOka79** [comment]
> A workaround would be obtaining your own client id & client secret, and place them in the `CLIENT_CREDENTIAL` variable in the script "cleaner.py".

Hi!
What can I do, when I'm using the binary version? (cleaner.exe under Windows)

**Comment by cfbao** [comment]
> What can I do, when I'm using the binary version?

Sorry but it isn't currently possible to use your own Google app client ID & secret with the binary version.

I will likely restructure the script/app to allow easy injection of user provided client ID & secret, and document that as the new standard way to use this script.
Reading Google's policies has made me feel like this script has a very slim chance of getting verified, and it'd be a lot of work on my side, which might not be worth it.

**Comment by cfbao** [comment]
Project deprecated. See [ReadMe](https://github.com/cfbao/google-drive-trash-cleaner/blob/master/README.md).
