### ISSUE TITLE
Delete using batch requests

### ISSUE THREAD

**Issue by fgrueninger** [cfbao/google-drive-trash-cleaner#15]
Hi, if I understand the output of cleaner.py correctly, this script doesn't use batch requests to delete files (so it deletes one-by-one / one file per request).

Can somebody confirm? It would be great if the script would use batch requests; I have millions of files in my trash and the script is pretty slow (don't know if the "searching" for files, or the deletion itself is slow; I started it with "-d 0").

Thanks :)

**Comment by cfbao** [comment]
Project deprecated. See [ReadMe](https://github.com/cfbao/google-drive-trash-cleaner/blob/master/README.md).
