### ISSUE TITLE
"No files to be deleted"

### ISSUE THREAD

**Issue by samsunix** [cfbao/google-drive-trash-cleaner#4]
There is 'some' files in Bin but example with command: 
```
python3 cleaner.py -v

No files to be deleted
```

**Comment by cfbao** [comment]
When were these files trashed? By default, only files trashed more than 30 days ago are listed/deleted. If you want to delete more recently trashed files, please use the -d option.

**Comment by samsunix** [comment]
yes, you are right. User error. with python3 cleaner.py -a -d 0 I got it working as expected and bin folder is empty.
