### ISSUE TITLE
Results not consistent with Google Drive

### ISSUE THREAD

**Issue by AlexDings** [cfbao/google-drive-trash-cleaner#5]
Running the script worked as expected and after running the same command "cleaner -a -d 2" I get the message "No files to be deleted". However, when I search for "is:trashed" is still seem to get a lot of files.

**Comment by cfbao** [comment]
Could you please confirm these "is:trashed" files you found were trashed more than 2 days ago?
If so, do they share any common attributes from what you can see?

**Comment by AlexDings** [comment]
Yes they are. 
After looking at the file details I think they are all moved to trash by my Desktop client.
Activity shows:
"Sep 22, 2017 **Computer**"

**Comment by cfbao** [comment]
Are these files owned by you? i.e. not shared files from someone else

**Comment by AlexDings** [comment]
They are indeed owned by me. They might shared with someone else though.

I must also say I "deleted" 10.000 files with the tool. Don't know if that matters.

**Comment by AlexDings** [comment]
There was indeed a Google caching issue.
So, the Google Drive Web interface was wrong and your app was right.
Amazing work.
