### ISSUE TITLE
Unicde Encode Errors

### ISSUE THREAD

**Issue by AlexDings** [cfbao/google-drive-trash-cleaner#7]
When files contain unicode characters you will encounter the following error:

Traceback (most recent call last):
  File "cleaner.py", line 433, in <module>
  File "cleaner.py", line 79, in main
  File "cleaner.py", line 259, in get_deletion_list
  File "cleaner.py", line 331, in found
  File "c:\python\python35-32\lib\encodings\cp437.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u2013' in position 58: character maps to <undefined>
Failed to execute script cleaner

Renaming the files works to resolve the issue.

**Comment by AlexDings** [comment]
I have python 3.6 installed on my PC but am using the .exe file because there was some other issue with running the .py script on my machine, caused by a known Windows bug without a fix yet.

I guess I will have to stick with remaning the files for now.
Thank you for your response

**Comment by cfbao** [comment]
I have updated the .exe file in 1.1.2 release to Python 3.6. It should solve your encoding problem.
